
default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: postgres
  password: <%= ENV['POKE_SIMPLE_API_DATABASE_PASSWORD'] %>
  database: poke_simple_api_development

test:
  <<: *default
  username: postgres
  password: <%= ENV['POKE_SIMPLE_API_DATABASE_PASSWORD'] %>
  database: poke_simple_api_test

production:
  <<: *default
  database: poke_simple_api_production
  username: postgres
  password: <%= ENV['POKE_SIMPLE_API_DATABASE_PASSWORD'] %>
